# docker-compose.yml
version: "3.9"

services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:1.15
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #     - 443:443
  #   networks:
  #     - my-network

  # postgres:
  #   container_name: postgres
  #   image: postgres:15.1
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - my-network
  #   volumes:
  #     - C:/postgresql/data/:/var/lib/postgresql/data
  #   env_file:
  #     - ./.env

networks:
  my-network:
