# docker-compose.yml
version: "3.9"

#green
services:
  api:
    container_name: spring-green
    # restart: always
    build: .
    ports:
      - "8082:8080"
    networks:
      - my-network

networks:
  my-network:
