# docker-compose.yml
version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data # 도커 컨테이너가 종료되면 데이터베이스도 사라져 버린다. 컨테이너가 종료돼도 데이터를 보존하기 위해 postgresql/data 폴더에 데이터베이스 데이터들을 저장한다.
    env_file:
      - ./.env

networks:
  my-network:
