# docker-compose.yml
version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    networks:
      - my-network
    volumes:
      - C:/postgresql/data/:/var/lib/postgresql/data
    env_file:
      - ./.env

networks:
  my-network:
